import { AlertCircle, Bug, CheckCircle2, ClipboardCheck, DatabaseBackup, FileClock, Plus, RefreshCw, Search, ShieldCheck, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { ShellPageActions } from './components/ShellPageActions';

const api = () => window.ValleyRuntime?.api?.uat || '/api/uat';
const localized = (locale, en, my) => locale === 'my' ? my : en;
const titleCase = (value) => String(value || '—').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const errorText = (error) => error.response?.data?.message || Object.values(error.response?.data?.errors || {})[0]?.[0] || 'Unable to load UAT readiness.';
const blankIssue = { module: 'foundation', title: '', steps: '', severity: 'medium', status: 'open', assigned_to: '', resolution: '' };

function State({ loading, children }) {
    return <div className="workspace-state uat-state">{loading ? <RefreshCw className="spin" size={22} /> : <AlertCircle size={22} />}<strong>{children}</strong></div>;
}

function Metric({ icon: Icon, label, value, hint, tone = '' }) {
    return <article className={`uat-metric ${tone}`}><span><Icon size={16} /></span><div><small>{label}</small><strong>{value}</strong><p>{hint}</p></div></article>;
}

function IssueDialog({ issue, options, saving, error, onChange, onClose, onSave }) {
    return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="master-dialog uat-dialog" role="dialog" aria-modal="true" aria-labelledby="uat-dialog-title" onSubmit={onSave}><header><div><p className="eyebrow">UAT issue</p><h2 id="uat-dialog-title">{issue.id ? `Update ${issue.code}` : 'Record test finding'}</h2></div><button className="icon-button" type="button" aria-label="Close issue form" onClick={onClose}><X size={16} /></button></header><div className="master-form-body">{error && <p className="form-alert">{error}</p>}<div className="master-form-grid"><label className="master-field">Module<select value={issue.module} onChange={(event) => onChange({ ...issue, module: event.target.value })}>{options.modules.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label className="master-field">Severity<select value={issue.severity} onChange={(event) => onChange({ ...issue, severity: event.target.value })}>{['low', 'medium', 'high', 'critical'].map((value) => <option value={value} key={value}>{titleCase(value)}</option>)}</select></label><label className="master-field wide">Finding title<input required maxLength="200" value={issue.title} onChange={(event) => onChange({ ...issue, title: event.target.value })} /></label><label className="master-field wide">Steps to reproduce<textarea rows="4" value={issue.steps || ''} onChange={(event) => onChange({ ...issue, steps: event.target.value })} /></label><label className="master-field">Status<select value={issue.status} onChange={(event) => onChange({ ...issue, status: event.target.value })}>{['open', 'in_progress', 'retest', 'resolved', 'closed'].map((value) => <option value={value} key={value}>{titleCase(value)}</option>)}</select></label><label className="master-field">Assign to<select value={issue.assigned_to || ''} onChange={(event) => onChange({ ...issue, assigned_to: event.target.value })}><option value="">Unassigned</option>{options.users.map((user) => <option value={user.id} key={user.id}>{user.name} · {user.role}</option>)}</select></label><label className="master-field wide">Resolution / retest note<textarea rows="3" value={issue.resolution || ''} onChange={(event) => onChange({ ...issue, resolution: event.target.value })} /></label></div></div><footer><button className="button" type="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}><ClipboardCheck size={15} />{saving ? 'Saving…' : 'Save finding'}</button></footer></form></div>;
}

function ReadinessOverview({ data }) {
    return <><div className="uat-module-grid">{(data.modules || []).map((module) => <article key={module.module}><span className={`uat-module-state ${module.status}`}><CheckCircle2 size={15} />{titleCase(module.status)}</span><small>Phase {module.phase}</small><h3>{module.label}</h3><p>{module.open_issues ? `${module.open_issues} issue(s) need attention` : 'Ready for guided acceptance testing'}</p></article>)}</div><div className="uat-two-column"><section className="master-panel uat-runbook"><header><div><p className="eyebrow">Release gate</p><h2>UAT run sequence</h2></div><ShieldCheck size={19} /></header>{['Reset deterministic demo data', 'Test each module with the listed role account', 'Record every defect with reproducible steps', 'Fix, retest, and resolve all critical/high findings', 'Create and verify a database backup before launch'].map((step, index) => <div key={step}><span>{index + 1}</span><p>{step}</p></div>)}</section><section className="master-panel uat-accounts"><header><div><p className="eyebrow">Test access</p><h2>Role accounts</h2></div></header>{(data.test_accounts || []).map((account) => <div key={account.app}><span><strong>{account.app}</strong><small>{account.role}</small></span><code>{account.email}</code></div>)}</section></div></>;
}

function IssuesTable({ state, filters, setFilters, canManage, onEdit }) {
    return <section className="master-panel"><div className="master-toolbar uat-toolbar"><label className="master-search"><Search size={14} /><input aria-label="Search UAT issues" placeholder="Search code or finding" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value, page: 1 })} /></label><select aria-label="Filter module" value={filters.module} onChange={(event) => setFilters({ ...filters, module: event.target.value, page: 1 })}><option value="">All modules</option>{state.options.modules.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select><select aria-label="Filter issue status" value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value, page: 1 })}><option value="">All statuses</option>{['open', 'in_progress', 'retest', 'resolved', 'closed'].map((value) => <option value={value} key={value}>{titleCase(value)}</option>)}</select></div>{state.loading ? <State loading>Loading test findings</State> : state.error ? <p className="inline-error">{state.error}</p> : !state.items.length ? <State>No UAT findings match this view.</State> : <><div className="master-table-wrap"><table className="master-table uat-issues-table"><thead><tr><th>Finding</th><th>Module</th><th>Severity</th><th>Status</th><th>Owner</th><th>Updated</th>{canManage && <th className="table-actions-header">Actions</th>}</tr></thead><tbody>{state.items.map((item) => <tr key={item.id}><td><strong>{item.code} · {item.title}</strong><span className="muted">{item.steps || 'No reproduction steps entered'}</span></td><td>{titleCase(item.module)}</td><td><span className={`status uat-${item.severity}`}>{titleCase(item.severity)}</span></td><td><span className={`status ${['resolved', 'closed'].includes(item.status) ? 'success' : item.status === 'retest' ? 'info' : 'warning'}`}>{titleCase(item.status)}</span></td><td>{item.assigned_name || 'Unassigned'}</td><td>{new Date(item.updated_at).toLocaleDateString()}</td>{canManage && <td className="table-actions-cell"><button className="button small" onClick={() => onEdit(item)}>Review</button></td>}</tr>)}</tbody></table></div><div className="master-pagination"><span>{state.meta.total} findings</span><div><button disabled={filters.page <= 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>‹</button><button disabled={filters.page >= state.meta.last_page} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>›</button></div></div></>}</section>;
}

function AuditTable({ state }) {
    return <section className="master-panel">{state.loading ? <State loading>Loading immutable activity history</State> : state.error ? <p className="inline-error">{state.error}</p> : !state.items.length ? <State>No mutation activity has been recorded yet.</State> : <div className="master-table-wrap"><table className="master-table uat-audit-table"><thead><tr><th>Time</th><th>User / app</th><th>Action</th><th>Endpoint</th><th>Entity</th><th>Result</th><th>Duration</th></tr></thead><tbody>{state.items.map((item) => <tr key={item.id}><td><strong>{new Date(item.created_at).toLocaleString()}</strong><span className="muted">{item.ip_address}</span></td><td><strong>{item.user_name || 'Public'}</strong><span className="muted">{titleCase(item.app)}</span></td><td><span className="status neutral">{titleCase(item.action)}</span></td><td><code>{item.method} {item.path}</code></td><td>{titleCase(item.entity_type)} {item.entity_id ? `#${item.entity_id}` : ''}</td><td>{item.status_code}</td><td>{item.duration_ms} ms</td></tr>)}</tbody></table></div>}</section>;
}

export function UatReadinessScreen({ locale = 'en', canManage = false }) {
    const [tab, setTab] = useState('readiness'); const [overview, setOverview] = useState({ loading: true, data: {}, error: '' }); const [issues, setIssues] = useState({ loading: true, items: [], meta: {}, options: { modules: [], users: [] }, error: '' }); const [audit, setAudit] = useState({ loading: true, items: [], error: '' }); const [filters, setFilters] = useState({ search: '', module: '', status: '', page: 1 }); const [refresh, setRefresh] = useState(0); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState('');
    useEffect(() => { window.axios.get(`${api()}/overview`).then(({ data }) => setOverview({ loading: false, data: data.data, error: '' })).catch((error) => setOverview({ loading: false, data: {}, error: errorText(error) })); }, [refresh]);
    useEffect(() => { let active = true; setIssues((value) => ({ ...value, loading: true })); window.axios.get(`${api()}/issues`, { params: filters }).then(({ data }) => active && setIssues({ loading: false, ...data.data, error: '' })).catch((error) => active && setIssues((value) => ({ ...value, loading: false, error: errorText(error) }))); return () => { active = false; }; }, [filters, refresh]);
    useEffect(() => { if (tab !== 'audit') return; setAudit((value) => ({ ...value, loading: true })); window.axios.get(`${api()}/audit-logs`).then(({ data }) => setAudit({ loading: false, ...data.data, error: '' })).catch((error) => setAudit({ loading: false, items: [], error: errorText(error) })); }, [tab, refresh]);
    const save = (event) => { event.preventDefault(); setSaving(true); setFormError(''); const previous = editing.id ? issues.items.find((row) => row.id === editing.id) || editing : null; const payload = { ...editing, assigned_to: editing.assigned_to || null }; const request = editing.id ? window.axios.put(`${api()}/issues/${editing.id}`, payload) : window.axios.post(`${api()}/issues`, payload); request.then(({ data }) => { const item = data.data.item; const normalizedSearch = filters.search.trim().toLowerCase(); const matches = (!filters.module || item.module === filters.module) && (!filters.status || item.status === filters.status) && (!normalizedSearch || `${item.code} ${item.title}`.toLowerCase().includes(normalizedSearch)); setIssues((current) => { const existed = current.items.some((row) => row.id === item.id); const withoutItem = current.items.filter((row) => row.id !== item.id); return { ...current, items: matches ? [item, ...withoutItem] : withoutItem, meta: { ...current.meta, total: Math.max(0, Number(current.meta?.total || 0) + (!existed && matches ? 1 : existed && !matches ? -1 : 0)) } }; }); setOverview((current) => { const openStatuses = ['open', 'in_progress', 'retest']; const resolvedStatuses = ['resolved', 'closed']; const summary = { ...(current.data.summary || {}) }; if (previous && openStatuses.includes(previous.status)) summary.open = Math.max(0, Number(summary.open || 0) - 1); if (previous && resolvedStatuses.includes(previous.status)) summary[previous.status] = Math.max(0, Number(summary[previous.status] || 0) - 1); if (openStatuses.includes(item.status)) summary.open = Number(summary.open || 0) + 1; if (resolvedStatuses.includes(item.status)) summary[item.status] = Number(summary[item.status] || 0) + 1; return { ...current, data: { ...current.data, summary } }; }); setEditing(null); setTab('issues'); }).catch((error) => setFormError(errorText(error))).finally(() => setSaving(false)); };
    const summary = overview.data.summary || {};
    return <section className="page uat-page"><div className="master-heading"><div><p className="eyebrow">{localized(locale, 'Phase 11 · Launch readiness', 'အဆင့် ၁၁ · စတင်အသုံးပြုရန် အသင့်')}</p><h1>{localized(locale, 'UAT & security center', 'UAT နှင့် လုံခြုံရေး ဗဟို')}</h1><span className="muted">Run role-based acceptance checks, track findings, and review the system mutation trail before launch.</span></div><ShellPageActions>{canManage && <button className="button primary" onClick={() => { setFormError(''); setEditing({ ...blankIssue }); }}><Plus size={15} />Record finding</button>}</ShellPageActions></div><div className="uat-metrics"><Metric icon={ClipboardCheck} label="Modules" value={summary.modules || 0} hint="Guided UAT sequence" /><Metric icon={Bug} label="Open findings" value={summary.open || 0} hint="Open, active, or retest" tone={summary.open ? 'warning' : 'success'} /><Metric icon={CheckCircle2} label="Resolved" value={(summary.resolved || 0) + (summary.closed || 0)} hint="Fixed and verified" tone="success" /><Metric icon={FileClock} label="Audit events" value={summary.audit_events || 0} hint="Successful mutations recorded" /><Metric icon={DatabaseBackup} label="Backup gate" value="Daily 02:00" hint="14-day operational retention" /></div><div className="uat-tabs" role="tablist"><button className={tab === 'readiness' ? 'is-active' : ''} onClick={() => setTab('readiness')}>Readiness</button><button className={tab === 'issues' ? 'is-active' : ''} onClick={() => setTab('issues')}>Findings <span>{summary.open || 0}</span></button><button className={tab === 'audit' ? 'is-active' : ''} onClick={() => setTab('audit')}>Audit log</button><button className="uat-refresh" aria-label="Refresh UAT data" onClick={() => setRefresh((value) => value + 1)}><RefreshCw size={14} /></button></div>{overview.loading ? <State loading>Calculating launch readiness</State> : overview.error ? <p className="inline-error">{overview.error}</p> : tab === 'readiness' ? <ReadinessOverview data={overview.data} /> : tab === 'issues' ? <IssuesTable state={issues} filters={filters} setFilters={setFilters} canManage={canManage} onEdit={(item) => { setFormError(''); setEditing({ ...item, assigned_to: item.assigned_to || '' }); }} /> : <AuditTable state={audit} />}{editing && <IssueDialog issue={editing} options={issues.options} saving={saving} error={formError} onChange={setEditing} onClose={() => setEditing(null)} onSave={save} />}</section>;
}
