import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import type { AxiosError } from 'axios';
import { apiClient } from '../../../packages/api-client/client';
import { Icon } from '../../../packages/design-system/Icon';
import { useI18n } from '../../../packages/i18n/I18nProvider';
import { MasterDataNavigation } from './MasterDataNavigation';

type Tab = 'roles' | 'assignments' | 'pricing' | 'costs' | 'audit';
interface Name { en: string; 'my-MM': string | null }
interface Option { public_id: string; code: string; name_en: string; name_my: string | null }
interface Role { id: string; code: string; name: Name; permissions: string[]; approval_limit_minor: number | null; assignments_count: number; status: string; version: number }
interface UserOption { public_id: string; name: string; email: string }
interface Assignment { id: string; user: { id: string; name: string; email: string }; role: { id: string; code: string; name: Name }; data_scope: string; branch_public_ids: string[]; status: string; version: number }
interface AccessData { roles: Role[]; assignments: Assignment[]; users: UserOption[]; branches: Option[]; permissions: string[] }
interface PriceBookOption extends Option { price_type: { code: string } }
interface PriceAssignment { id: string; price_book: { id: string; code: string; name: Name; price_type: string }; target_type: string; target_key: string; priority: number; effective_from: string; effective_to: string | null; status: string; version: number }
interface Cost { id: string; warehouse: { id: string; code: string; name: Name }; sku: { id: string; code: string; name: Name }; unit_cost_minor: number; currency: string; valuation_method: string; effective_from: string; effective_to: string | null; approval_status: string; reason: string; status: string; version: number }
interface PricingData { assignments: PriceAssignment[]; costs: Cost[]; price_books: PriceBookOption[]; customers: (Option & { classification: string | null })[]; ways: Option[]; warehouses: Option[]; skus: Option[] }
interface AuditEvent { id: string; action: string; entity_type: string; entity_id: string | null; reason: string | null; correlation_id: string | null; created_at: string }
interface ApiError { message?: string; errors?: Record<string, string[]> }

export function GovernancePage() {
    const { locale, t } = useI18n(); const [tab, setTab] = useState<Tab>('roles'); const [access, setAccess] = useState<AccessData | null>(null); const [pricing, setPricing] = useState<PricingData | null>(null); const [audit, setAudit] = useState<AuditEvent[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(false); const [refreshKey, setRefreshKey] = useState(0); const [dialog, setDialog] = useState<'role' | 'user' | 'assignment' | 'price' | 'cost' | null>(null); const [errors, setErrors] = useState<Record<string, string[]>>({}); const [submitting, setSubmitting] = useState(false); const [flash, setFlash] = useState<string | null>(null);
    const [roleForm, setRoleForm] = useState({ code: '', name_en: '', name_my: '', permissions: [] as string[], approval_limit_minor: '', status: 'active' }); const [userForm, setUserForm] = useState({ name: '', email: '', password: '' }); const [assignmentForm, setAssignmentForm] = useState({ user_public_id: '', role_public_id: '', data_scope: 'organization', branch_public_ids: [] as string[] }); const [priceForm, setPriceForm] = useState({ price_book_public_id: '', target_type: 'customer', target_key: '', priority: 0, effective_from: new Date().toISOString().slice(0, 10), effective_to: '', status: 'active' }); const [costForm, setCostForm] = useState({ warehouse_public_id: '', sku_public_id: '', unit_cost_minor: 0, currency: 'MMK', valuation_method: 'weighted_average', effective_from: new Date().toISOString().slice(0, 10), effective_to: '', reason: '' });
    const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setLoadError(false); try { const [a, p, h] = await Promise.all([apiClient.get<{ data: AccessData }>('/master-data/access-controls', { signal }), apiClient.get<{ data: PricingData }>('/master-data/pricing-controls', { signal }), apiClient.get<{ data: AuditEvent[] }>('/master-data/audit-history', { signal })]); setAccess(a.data.data); setPricing(p.data.data); setAudit(h.data.data); } catch { if (!signal?.aborted) setLoadError(true); } finally { if (!signal?.aborted) setLoading(false); } }, []);
    useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load, refreshKey]);
    const localized = (name: Name) => name[locale] || name.en; const optionName = (item: Option) => locale === 'my-MM' ? item.name_my || item.name_en : item.name_en; const close = () => { if (!submitting) { setDialog(null); setErrors({}); } }; const fail = (error: unknown) => { const response = (error as AxiosError<ApiError>).response; setErrors(response?.data.errors ?? { form: [response?.data.message ?? t('governanceConflict')] }); }; const saved = (message: string) => { setFlash(message); setDialog(null); setRefreshKey((v) => v + 1); };
    const begin = () => { setErrors({}); if (tab === 'roles') { setRoleForm({ code: '', name_en: '', name_my: '', permissions: ['master_data.view'], approval_limit_minor: '', status: 'active' }); setDialog('role'); } else if (tab === 'assignments') { setAssignmentForm({ user_public_id: access?.users[0]?.public_id ?? '', role_public_id: access?.roles.find((r) => r.status === 'active')?.id ?? '', data_scope: 'organization', branch_public_ids: [] }); setDialog('assignment'); } else if (tab === 'pricing') { setPriceForm({ price_book_public_id: pricing?.price_books[0]?.public_id ?? '', target_type: 'customer', target_key: pricing?.customers[0]?.public_id ?? '', priority: 0, effective_from: new Date().toISOString().slice(0, 10), effective_to: '', status: 'active' }); setDialog('price'); } else { setCostForm({ warehouse_public_id: pricing?.warehouses[0]?.public_id ?? '', sku_public_id: pricing?.skus[0]?.public_id ?? '', unit_cost_minor: 0, currency: 'MMK', valuation_method: 'weighted_average', effective_from: new Date().toISOString().slice(0, 10), effective_to: '', reason: '' }); setDialog('cost'); } };
    async function submitRole(event: FormEvent) { event.preventDefault(); setSubmitting(true); try { await apiClient.post('/master-data/access-controls/roles', { ...roleForm, approval_limit_minor: roleForm.approval_limit_minor === '' ? null : Number(roleForm.approval_limit_minor) }); saved(t('roleCreated')); } catch (e) { fail(e); } finally { setSubmitting(false); } }
    async function submitUser(event: FormEvent) { event.preventDefault(); setSubmitting(true); try { await apiClient.post('/master-data/access-controls/users', userForm); saved(t('userCreated')); } catch (e) { fail(e); } finally { setSubmitting(false); } }
    async function submitAssignment(event: FormEvent) { event.preventDefault(); setSubmitting(true); try { await apiClient.post('/master-data/access-controls/assignments', assignmentForm); saved(t('assignmentCreated')); } catch (e) { fail(e); } finally { setSubmitting(false); } }
    async function submitPrice(event: FormEvent) { event.preventDefault(); setSubmitting(true); try { await apiClient.post('/master-data/pricing-controls/assignments', { ...priceForm, effective_to: priceForm.effective_to || null }); saved(t('priceAssignmentCreated')); } catch (e) { fail(e); } finally { setSubmitting(false); } }
    async function submitCost(event: FormEvent) { event.preventDefault(); setSubmitting(true); try { await apiClient.post('/master-data/pricing-controls/costs', { ...costForm, effective_to: costForm.effective_to || null }); saved(t('costCreated')); } catch (e) { fail(e); } finally { setSubmitting(false); } }
    async function revoke(item: Assignment) { const reason = window.prompt(t('archiveReason')); if (!reason) return; try { await apiClient.patch(`/master-data/access-controls/assignments/${item.id}/revoke`, { version: item.version, reason }); saved(t('assignmentRevoked')); } catch (e) { fail(e); } }
    async function approveCost(item: Cost) { const reason = window.prompt(t('approvalReason')); if (!reason) return; try { await apiClient.patch(`/master-data/pricing-controls/costs/${item.id}/approve`, { version: item.version, reason }); saved(t('costApproved')); } catch (e) { fail(e); } }
    const actionLabel = tab === 'roles' ? t('addRole') : tab === 'assignments' ? t('assignRole') : tab === 'pricing' ? t('addPriceAssignment') : t('addProductCost');

    return <><section className="page-heading"><div><p className="eyebrow">{t('phaseOne')}</p><h1>{t('governanceAndPricing')}</h1><p>{t('governanceDescription')}</p></div>{tab !== 'audit' && <div className="heading-actions">{tab === 'assignments' && <button className="button button--secondary" onClick={() => { setUserForm({ name: '', email: '', password: '' }); setDialog('user'); }}>{t('addUser')}</button>}<button className="button button--primary" onClick={begin}><Icon name="plus" size={16} />{actionLabel}</button></div>}</section><MasterDataNavigation /><nav className="location-register-tabs control-tabs" aria-label={t('governanceAndPricing')}>{(['roles', 'assignments', 'pricing', 'costs', 'audit'] as Tab[]).map((item) => <button key={item} className={tab === item ? 'is-active' : ''} onClick={() => setTab(item)}>{item === 'roles' ? t('roles') : item === 'assignments' ? t('roleAssignments') : item === 'pricing' ? t('priceAssignments') : item === 'costs' ? t('productCosts') : t('auditHistory')}</button>)}</nav>{flash && <div className="flash-message flash-message--success"><span className="status-dot status-dot--success" />{flash}</div>}
        <article className="panel master-register"><div className="panel-heading"><div><p className="eyebrow">{t('releaseControls')}</p><h2>{tab === 'roles' ? t('roles') : tab === 'assignments' ? t('roleAssignments') : tab === 'pricing' ? t('priceAssignments') : tab === 'costs' ? t('productCosts') : t('auditHistory')}</h2></div></div>{loadError ? <div className="empty-state register-state"><strong>{t('errorLoadingGovernance')}</strong><button className="button button--secondary" onClick={() => setRefreshKey((v) => v + 1)}>{t('retry')}</button></div> : <div className="table-region master-table" tabIndex={0} aria-busy={loading}><GovernanceTable tab={tab} access={access} pricing={pricing} audit={audit} localized={localized} loading={loading} revoke={revoke} approveCost={approveCost} /></div>}</article>
        {dialog === 'role' && access && <Modal title={t('addRole')} close={close}><form onSubmit={submitRole}><Body errors={errors}><Field label={t('code')}><input value={roleForm.code} onChange={(e) => setRoleForm({ ...roleForm, code: e.target.value })} required /></Field><Field label={t('englishName')}><input value={roleForm.name_en} onChange={(e) => setRoleForm({ ...roleForm, name_en: e.target.value })} required /></Field><Field label={t('myanmarName')}><input value={roleForm.name_my} onChange={(e) => setRoleForm({ ...roleForm, name_my: e.target.value })} /></Field><Field label={t('approvalLimit')}><input type="number" min={0} value={roleForm.approval_limit_minor} onChange={(e) => setRoleForm({ ...roleForm, approval_limit_minor: e.target.value })} /></Field><div className="form-field form-field--wide"><span>{t('permissions')}</span><div className="checkbox-grid">{access.permissions.map((permission) => <label key={permission}><input type="checkbox" checked={roleForm.permissions.includes(permission)} onChange={(e) => setRoleForm({ ...roleForm, permissions: e.target.checked ? [...roleForm.permissions, permission] : roleForm.permissions.filter((p) => p !== permission) })} />{permission}</label>)}</div></div></Body><Actions close={close} busy={submitting} /></form></Modal>}
        {dialog === 'user' && <Modal title={t('addUser')} close={close}><form onSubmit={submitUser}><Body errors={errors}><Field label={t('name')}><input value={userForm.name} onChange={(e) => setUserForm({ ...userForm, name: e.target.value })} required /></Field><Field label={t('email')}><input type="email" value={userForm.email} onChange={(e) => setUserForm({ ...userForm, email: e.target.value })} required /></Field><Field label={t('temporaryPassword')} wide><input type="password" minLength={12} value={userForm.password} onChange={(e) => setUserForm({ ...userForm, password: e.target.value })} required /></Field></Body><Actions close={close} busy={submitting} /></form></Modal>}
        {dialog === 'assignment' && access && <Modal title={t('assignRole')} close={close}><form onSubmit={submitAssignment}><Body errors={errors}><Field label={t('user')}><select value={assignmentForm.user_public_id} onChange={(e) => setAssignmentForm({ ...assignmentForm, user_public_id: e.target.value })}>{access.users.map((u) => <option key={u.public_id} value={u.public_id}>{u.name} · {u.email}</option>)}</select></Field><Field label={t('role')}><select value={assignmentForm.role_public_id} onChange={(e) => setAssignmentForm({ ...assignmentForm, role_public_id: e.target.value })}>{access.roles.filter((r) => r.status === 'active').map((r) => <option key={r.id} value={r.id}>{r.code} · {localized(r.name)}</option>)}</select></Field><Field label={t('dataScope')}><select value={assignmentForm.data_scope} onChange={(e) => setAssignmentForm({ ...assignmentForm, data_scope: e.target.value })}><option value="organization">{t('organizationWide')}</option><option value="branches">{t('selectedBranches')}</option></select></Field>{assignmentForm.data_scope === 'branches' && <div className="form-field form-field--wide"><span>{t('branches')}</span><div className="checkbox-grid">{access.branches.map((b) => <label key={b.public_id}><input type="checkbox" checked={assignmentForm.branch_public_ids.includes(b.public_id)} onChange={(e) => setAssignmentForm({ ...assignmentForm, branch_public_ids: e.target.checked ? [...assignmentForm.branch_public_ids, b.public_id] : assignmentForm.branch_public_ids.filter((id) => id !== b.public_id) })} />{b.code} · {optionName(b)}</label>)}</div></div>}</Body><Actions close={close} busy={submitting} /></form></Modal>}
        {dialog === 'price' && pricing && <Modal title={t('addPriceAssignment')} close={close}><form onSubmit={submitPrice}><Body errors={errors}><Field label={t('priceBook')}><select value={priceForm.price_book_public_id} onChange={(e) => setPriceForm({ ...priceForm, price_book_public_id: e.target.value })}>{pricing.price_books.map((b) => <option key={b.public_id} value={b.public_id}>{b.code} · {optionName(b)}</option>)}</select></Field><Field label={t('assignmentTarget')}><select value={priceForm.target_type} onChange={(e) => setPriceForm({ ...priceForm, target_type: e.target.value, target_key: e.target.value === 'customer' ? pricing.customers[0]?.public_id ?? '' : e.target.value === 'way' ? pricing.ways[0]?.public_id ?? '' : '' })}><option value="customer">{t('specificCustomer')}</option><option value="customer_classification">{t('customerClassification')}</option><option value="way">{t('way')}</option></select></Field><Field label={t('targetValue')}>{priceForm.target_type === 'customer' ? <select value={priceForm.target_key} onChange={(e) => setPriceForm({ ...priceForm, target_key: e.target.value })}>{pricing.customers.map((c) => <option key={c.public_id} value={c.public_id}>{c.code} · {optionName(c)}</option>)}</select> : priceForm.target_type === 'way' ? <select value={priceForm.target_key} onChange={(e) => setPriceForm({ ...priceForm, target_key: e.target.value })}>{pricing.ways.map((w) => <option key={w.public_id} value={w.public_id}>{w.code} · {optionName(w)}</option>)}</select> : <input value={priceForm.target_key} onChange={(e) => setPriceForm({ ...priceForm, target_key: e.target.value })} required />}</Field><Field label={t('priority')}><input type="number" min={0} value={priceForm.priority} onChange={(e) => setPriceForm({ ...priceForm, priority: Number(e.target.value) })} /></Field><Dates from={priceForm.effective_from} to={priceForm.effective_to} setFrom={(v) => setPriceForm({ ...priceForm, effective_from: v })} setTo={(v) => setPriceForm({ ...priceForm, effective_to: v })} /></Body><Actions close={close} busy={submitting} /></form></Modal>}
        {dialog === 'cost' && pricing && <Modal title={t('addProductCost')} close={close}><form onSubmit={submitCost}><Body errors={errors}><Field label={t('warehouse')}><select value={costForm.warehouse_public_id} onChange={(e) => setCostForm({ ...costForm, warehouse_public_id: e.target.value })}>{pricing.warehouses.map((w) => <option key={w.public_id} value={w.public_id}>{w.code} · {optionName(w)}</option>)}</select></Field><Field label={t('sku')}><select value={costForm.sku_public_id} onChange={(e) => setCostForm({ ...costForm, sku_public_id: e.target.value })}>{pricing.skus.map((s) => <option key={s.public_id} value={s.public_id}>{s.code} · {optionName(s)}</option>)}</select></Field><Field label={t('unitCost')}><input type="number" min={0} value={costForm.unit_cost_minor} onChange={(e) => setCostForm({ ...costForm, unit_cost_minor: Number(e.target.value) })} /></Field><Field label={t('valuationMethod')}><select value="weighted_average" disabled><option value="weighted_average">{t('weightedAverage')}</option></select></Field><Dates from={costForm.effective_from} to={costForm.effective_to} setFrom={(v) => setCostForm({ ...costForm, effective_from: v })} setTo={(v) => setCostForm({ ...costForm, effective_to: v })} /><Field label={t('reason')} wide><textarea rows={3} value={costForm.reason} onChange={(e) => setCostForm({ ...costForm, reason: e.target.value })} required /></Field></Body><Actions close={close} busy={submitting} /></form></Modal>}
    </>;
}

function GovernanceTable({ tab, access, pricing, audit, localized, loading, revoke, approveCost }: { tab: Tab; access: AccessData | null; pricing: PricingData | null; audit: AuditEvent[]; localized: (name: Name) => string; loading: boolean; revoke: (item: Assignment) => void; approveCost: (item: Cost) => void }) {
    const { t } = useI18n();
    if (loading) return <table><tbody>{Array.from({ length: 5 }, (_, i) => <tr className="skeleton-row" key={i}><td><span /></td><td><span /></td><td><span /></td></tr>)}</tbody></table>;
    if (tab === 'roles') return <table><thead><tr><th>{t('role')}</th><th>{t('permissions')}</th><th>{t('approvalLimit')}</th><th>{t('assignments')}</th><th>{t('status')}</th></tr></thead><tbody>{access?.roles.map((r) => <tr key={r.id}><td className="identity-cell"><strong>{r.code}</strong><small>{localized(r.name)}</small></td><td>{r.permissions.length}</td><td>{r.approval_limit_minor?.toLocaleString() ?? '—'}</td><td>{r.assignments_count}</td><td>{r.status}</td></tr>)}</tbody></table>;
    if (tab === 'assignments') return <table><thead><tr><th>{t('user')}</th><th>{t('role')}</th><th>{t('dataScope')}</th><th>{t('status')}</th><th>{t('actions')}</th></tr></thead><tbody>{access?.assignments.map((a) => <tr key={a.id}><td className="identity-cell"><strong>{a.user.name}</strong><small>{a.user.email}</small></td><td>{a.role.code}</td><td>{a.data_scope === 'organization' ? t('organizationWide') : `${a.branch_public_ids.length} ${t('branches')}`}</td><td>{a.status}</td><td>{a.status === 'active' && <button className="button button--secondary" onClick={() => void revoke(a)}>{t('revoke')}</button>}</td></tr>)}</tbody></table>;
    if (tab === 'pricing') return <table><thead><tr><th>{t('priceBook')}</th><th>{t('assignmentTarget')}</th><th>{t('priority')}</th><th>{t('effectiveFrom')}</th><th>{t('status')}</th></tr></thead><tbody>{pricing?.assignments.map((a) => <tr key={a.id}><td className="identity-cell"><strong>{a.price_book.code}</strong><small>{a.price_book.price_type}</small></td><td>{a.target_type}<small>{a.target_key}</small></td><td>{a.priority}</td><td>{a.effective_from}<small>{a.effective_to ?? '—'}</small></td><td>{a.status}</td></tr>)}</tbody></table>;
    if (tab === 'audit') return <table><thead><tr><th>{t('action')}</th><th>{t('entity')}</th><th>{t('reason')}</th><th>{t('correlationId')}</th><th>{t('createdAt')}</th></tr></thead><tbody>{audit.map((event) => <tr key={event.id}><td>{event.action}</td><td className="identity-cell"><strong>{event.entity_type}</strong><small>{event.entity_id ?? '—'}</small></td><td>{event.reason ?? '—'}</td><td>{event.correlation_id ?? '—'}</td><td>{new Date(event.created_at).toLocaleString()}</td></tr>)}</tbody></table>;
    return <table><thead><tr><th>{t('sku')}</th><th>{t('warehouse')}</th><th>{t('unitCost')}</th><th>{t('effectiveFrom')}</th><th>{t('approval')}</th><th>{t('actions')}</th></tr></thead><tbody>{pricing?.costs.map((c) => <tr key={c.id}><td>{c.sku.code}</td><td>{c.warehouse.code}</td><td>{c.unit_cost_minor.toLocaleString()} {c.currency}</td><td>{c.effective_from}</td><td>{c.approval_status}</td><td>{c.approval_status === 'pending' && <button className="button button--secondary" onClick={() => void approveCost(c)}>{t('approve')}</button>}</td></tr>)}</tbody></table>;
}
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { const { t } = useI18n(); return <div className="modal-backdrop"><section className="dialog" role="dialog" aria-modal="true" aria-label={title}><header className="dialog-header"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label={t('closeDialog')}><Icon name="close" /></button></header>{children}</section></div>; }
function Body({ errors, children }: { errors: Record<string, string[]>; children: ReactNode }) { return <div className="dialog-body form-grid">{errors.form && <p className="form-error form-error--wide">{errors.form[0]}</p>}{children}</div>; }
function Actions({ close, busy }: { close: () => void; busy: boolean }) { const { t } = useI18n(); return <footer className="dialog-footer"><button type="button" className="button button--secondary" onClick={close}>{t('cancel')}</button><button className="button button--primary" disabled={busy}>{busy ? t('saving') : t('save')}</button></footer>; }
function Field({ label, wide, children }: { label: string; wide?: boolean; children: ReactNode }) { return <label className={wide ? 'form-field form-field--wide' : 'form-field'}><span>{label}</span>{children}</label>; }
function Dates({ from, to, setFrom, setTo }: { from: string; to: string; setFrom: (v: string) => void; setTo: (v: string) => void }) { const { t } = useI18n(); return <><Field label={t('effectiveFrom')}><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} required /></Field><Field label={t('effectiveTo')}><input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></Field></>; }
